
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Table table5;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Entry entry_b;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Entry entry_x1;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Entry entry_y1;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Entry entry_a;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Entry entry_x2;
	
	private global::Gtk.Label label14;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Entry entry_y2;
	
	private global::Gtk.Label label15;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.HBox hbox13;
	
	private global::Gtk.Label label20;
	
	private global::Gtk.Entry entry4;
	
	private global::Gtk.HBox hbox14;
	
	private global::Gtk.Label label21;
	
	private global::Gtk.Entry entry5;
	
	private global::Gtk.HBox hbox15;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button button2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.table5 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.entry_b = new global::Gtk.Entry ();
		this.entry_b.CanFocus = true;
		this.entry_b.Name = "entry_b";
		this.entry_b.IsEditable = true;
		this.entry_b.InvisibleChar = '●';
		this.hbox10.Add (this.entry_b);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.entry_b]));
		w1.Position = 0;
		this.table5.Add (this.hbox10);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox10]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry_x1 = new global::Gtk.Entry ();
		this.entry_x1.CanFocus = true;
		this.entry_x1.Name = "entry_x1";
		this.entry_x1.IsEditable = true;
		this.entry_x1.InvisibleChar = '●';
		this.hbox3.Add (this.entry_x1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry_x1]));
		w3.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("x");
		this.hbox3.Add (this.label11);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label11]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.table5.Add (this.hbox3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox3]));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.entry_y1 = new global::Gtk.Entry ();
		this.entry_y1.CanFocus = true;
		this.entry_y1.Name = "entry_y1";
		this.entry_y1.IsEditable = true;
		this.entry_y1.InvisibleChar = '●';
		this.hbox6.Add (this.entry_y1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entry_y1]));
		w6.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("y = ");
		this.hbox6.Add (this.label12);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label12]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.table5.Add (this.hbox6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox6]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.entry_a = new global::Gtk.Entry ();
		this.entry_a.CanFocus = true;
		this.entry_a.Name = "entry_a";
		this.entry_a.IsEditable = true;
		this.entry_a.InvisibleChar = '●';
		this.hbox7.Add (this.entry_a);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entry_a]));
		w9.Position = 0;
		this.table5.Add (this.hbox7);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox7]));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.entry_x2 = new global::Gtk.Entry ();
		this.entry_x2.CanFocus = true;
		this.entry_x2.Name = "entry_x2";
		this.entry_x2.IsEditable = true;
		this.entry_x2.InvisibleChar = '●';
		this.hbox8.Add (this.entry_x2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.entry_x2]));
		w11.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("x");
		this.hbox8.Add (this.label14);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label14]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.table5.Add (this.hbox8);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox8]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.entry_y2 = new global::Gtk.Entry ();
		this.entry_y2.CanFocus = true;
		this.entry_y2.Name = "entry_y2";
		this.entry_y2.IsEditable = true;
		this.entry_y2.InvisibleChar = '●';
		this.hbox9.Add (this.entry_y2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entry_y2]));
		w14.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("y = ");
		this.hbox9.Add (this.label15);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label15]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.table5.Add (this.hbox9);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox9]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox3.Add (this.table5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table5]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("x = ");
		this.hbox13.Add (this.label20);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label20]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.Sensitive = false;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.hbox13.Add (this.entry4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.entry4]));
		w19.Position = 1;
		this.vbox6.Add (this.hbox13);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox13]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("y = ");
		this.hbox14.Add (this.label21);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label21]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry ();
		this.entry5.Sensitive = false;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = false;
		this.entry5.InvisibleChar = '●';
		this.hbox14.Add (this.entry5);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.entry5]));
		w22.Position = 1;
		this.vbox6.Add (this.hbox14);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox14]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Решений нет или их бесконечное количество");
		this.hbox15.Add (this.label1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label1]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox6.Add (this.hbox15);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox15]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.hbox1.Add (this.vbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox6]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Решить систему уравнений");
		this.hbox2.Add (this.button2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button2]));
		w28.Position = 0;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1326;
		this.DefaultHeight = 830;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
